name: Lint & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.13']

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v4

      - name: Install Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install dependencies ⚙️
        run: |
          python -m pip install -U pip hatch
          hatch env create

      - name: Log Python environment ✏️
        run: |
          hatch run python -m pip freeze

      - name: black ◼️
        run: hatch run lint_black

      - name: flake8 ❄️
        run: hatch run lint_flake8

      - name: mypy 🧐
        run: hatch run lint_mypy

      - name: bandit 🦝
        run: hatch run lint_bandit

      - name: pytest tests 👓
        run: |
          pushd src/tests/
          hatch run test
          popd

      - name: pytest benchmark 📈
        run: hatch run benchmark

      - name: sphinx build 🐪
        run: hatch run docbuild
